// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"gear/Parameters","status":false,"description":"the gear plugin that allow to improve the splash screen system","parameters":{"playMe":"true","logos":"[\"{\\\"filename\\\":\\\"\\\",\\\"duration\\\":\\\"120\\\",\\\"me\\\":\\\"\\\"}\"]"}},
{"name":"gear-tools","status":false,"description":"the gear plugin that allow to improve the splash screen system","parameters":{"playMe":"true","fadeSpeed":"24","logos":"[\"{\\\"filename\\\":\\\"GameOver\\\",\\\"duration\\\":\\\"120\\\",\\\"me\\\":\\\"\\\"}\",\"{\\\"filename\\\":\\\"Splash\\\",\\\"duration\\\":\\\"120\\\",\\\"me\\\":\\\"\\\"}\"]"}},
{"name":"gear/TEST","status":true,"description":"","parameters":{}}
];
