import {
    Container,
    Graphics,
    RenderTexture,
    Sprite,
    Renderer,
} from 'pixi.js';
import { PingPongBuffer } from './PingPongBuffer.ts';

// @experimental its a solution generated by claude I am just not sure how to approach but its seems to work?
export class WindowLayer extends Container {

    // Ping-pong buffer for claimed regions — swap after each stamp to avoid
    // read/write hazard on the same texture.
    private _claimedBuffer: PingPongBuffer | null = null;

    // Graphics used to stamp each window's shape into the claimed buffer.
    private _claimedGraphics: Graphics = new Graphics();

    // Pool of RenderTextures for baking inverted masks — one slot per window
    // below the topmost. Avoids per-frame allocation.
    private _maskPool: RenderTexture[] = [];

    constructor() {
        super();

        this.onRender = (renderer: Renderer) => {
            this._renderWindowLayer(renderer);
        };
    }

    // -------------------------------------------------------------------------
    // Called every frame by the engine.
    // -------------------------------------------------------------------------
    update() {
        for (const child of this.children) {
            if ((child as any).update) {
                (child as any).update();
            }
        }
    }

    // -------------------------------------------------------------------------
    // Lazily create or resize the ping-pong buffer to match screen dimensions.
    // -------------------------------------------------------------------------
    private _ensureClaimedBuffer(renderer: Renderer): PingPongBuffer {
        const sw = renderer.width;
        const sh = renderer.height;

        if (!this._claimedBuffer) {
            this._claimedBuffer = new PingPongBuffer({ width: sw, height: sh });
        } else if (
            this._claimedBuffer.getSource().width !== sw ||
            this._claimedBuffer.getSource().height !== sh
        ) {
            this._claimedBuffer.resize(sw, sh);
        }

        return this._claimedBuffer;
    }

    // -------------------------------------------------------------------------
    // Ensure the mask pool has enough textures at the right size.
    // Pool size = windows.length - 1 (topmost window never needs a mask).
    // -------------------------------------------------------------------------
    private _ensureMaskPool(renderer: Renderer, count: number): void {
        const sw = renderer.width;
        const sh = renderer.height;

        for (let i = 0; i < this._maskPool.length; i++) {
            const tex = this._maskPool[i];
            if (tex.width !== sw || tex.height !== sh) {
                tex.destroy(true);
                this._maskPool[i] = RenderTexture.create({ width: sw, height: sh });
            }
        }

        while (this._maskPool.length < count) {
            this._maskPool.push(RenderTexture.create({ width: sw, height: sh }));
        }
    }

    // -------------------------------------------------------------------------
    // Core render logic — called via onRender each frame.
    // -------------------------------------------------------------------------
    private _renderWindowLayer(renderer: Renderer): void {
        const windows = this.children.filter(
            w => (w as any)._isWindow && w.visible && (w as any).openness > 0
        );
        const nonWindows = this.children.filter(
            w => !(w as any)._isWindow && w.visible
        );

        if (windows.length === 0) return;

        const sw = renderer.width;
        const sh = renderer.height;
        const worldTransform = this.worldTransform;

        const claimedBuffer = this._ensureClaimedBuffer(renderer);
        this._ensureMaskPool(renderer, windows.length - 1);

        // Save original renderability — restored in finally even if we throw.
        const originalRenderable = new Map<any, boolean>();
        for (const w of [...windows, ...nonWindows]) {
            originalRenderable.set(w, (w as any).renderable);
            (w as any).renderable = false;
        }

        try {
            // Clear both buffers at the start of the frame so no stale
            // claimed regions bleed in from the previous frame.
            claimedBuffer.clearAll();

            // Process windows top-to-bottom.
            // Last child = topmost, rendered first with no mask.
            for (let i = windows.length - 1; i >= 0; i--) {
                const win = windows[i] as any;
                const isTopmost = i === windows.length - 1;

                if (!isTopmost) {
                    // Bake inverted mask into the pool slot for this depth.
                    // Inverted = white everywhere EXCEPT the claimed regions,
                    // so the alpha mask keeps unclaimed pixels and cuts claimed ones.
                    const poolIndex = windows.length - 2 - i;
                    const invertedTex = this._maskPool[poolIndex];

                    const bg = new Graphics()
                        .rect(0, 0, sw, sh)
                        .fill({ color: 0xffffff, alpha: 1 });

                    // Read from the current SOURCE — safe because we write the
                    // stamp to the TARGET and swap after, never the same texture.
                    const eraser = new Sprite(claimedBuffer.getSource());
                    eraser.blendMode = 'erase';

                    const maskContainer = new Container();
                    maskContainer.addChild(bg, eraser);

                    renderer.render({
                        container: maskContainer,
                        target: invertedTex,
                        clear: true,
                    });

                    maskContainer.destroy({ children: true });

                    // Sprite mask → PixiJS v8 routes this as an AlphaMask.
                    win.mask = new Sprite(invertedTex);
                }

                // Render the window — pass worldTransform so parent scale/
                // position (e.g. a scaled stage) is respected.
                win.renderable = true;
                renderer.render({
                    container: win,
                    transform: worldTransform,
                });
                win.renderable = false;

                // Detach mask (pool texture stays alive, just unlink it).
                if (win.mask) {
                    (win.mask as Sprite).destroy();
                    win.mask = null;
                }

                // Stamp this window's shape into the TARGET buffer.
                this._claimedGraphics.clear();
                win.drawShape(this._claimedGraphics);

                renderer.render({
                    container: this._claimedGraphics,
                    target: claimedBuffer.getTarget(), // write to TARGET
                    clear: false,                       // accumulate stamps
                });

                // Swap — TARGET (with new stamp) becomes SOURCE for next read.
                claimedBuffer.swap();
            }

            // Non-window children render on top as normal.
            for (const child of nonWindows) {
                (child as any).renderable = true;
                renderer.render({
                    container: child as Container,
                    transform: worldTransform,
                });
                (child as any).renderable = false;
            }

        } finally {
            // Always restore original renderability.
            for (const [w, val] of originalRenderable) {
                (w as any).renderable = val;
            }
        }
    }

    // -------------------------------------------------------------------------
    // Cleanup
    // -------------------------------------------------------------------------
    override destroy() {
        this._claimedBuffer?.destroy();
        this._claimedBuffer = null;

        this._claimedGraphics.destroy();

        for (const tex of this._maskPool) tex.destroy(true);
        this._maskPool = [];

        super.destroy();
    }
}
